name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print working directory and its content
        run: pwd | ls -la
      - name: Build 
        working-directory: project2
        run: |
          cargo build --verbose
      - name: Run tests
        working-directory: project2
        run: cargo test --verbose
