name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./project2
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./project2
        cargo test --verbose

